# Generated by Django 4.1.2 on 2023-01-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckAddedGlossaryByUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Термин")),
                ("description", models.TextField(verbose_name="Описание")),
                ("isChecked", models.BooleanField(verbose_name="Проверено?")),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("email", models.EmailField(max_length=100, verbose_name="Логин")),
            ],
            options={
                "verbose_name": "Глоссарий",
                "verbose_name_plural": "Глоссарий",
            },
        ),
        migrations.CreateModel(
            name="Glossary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Термин")),
                ("description", models.TextField(verbose_name="Описание")),
                ("isFavourite", models.BooleanField(verbose_name="Избранный")),
            ],
        ),
    ]
